# Generated by Django 4.2.16 on 2024-09-18 04:51

import candidates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('party_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party_initial', models.CharField(blank=True, max_length=255, null=True)),
                ('party_color', models.CharField(blank=True, max_length=255, null=True)),
                ('year_formed', models.CharField(blank=True, max_length=255, null=True)),
                ('founder', models.CharField(blank=True, max_length=255, null=True)),
                ('party_logo', models.ImageField(blank=True, null=True, upload_to=candidates.models.upload_party_logo_path)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prez_can_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.models.upload_prez_can_photo_path)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('candidate_type', models.CharField(blank=True, choices=[('Independent', 'Independent'), ('Main Stream', 'Main Stream')], max_length=100, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezi_candidate_party', to='candidates.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyStandingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('won', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_standing_candidates', to='candidates.party')),
                ('standing_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_standing_candidates', to='candidates.presidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='PartyPresidentailPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_presidential_primaries', to='candidates.presidentialcandidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_presidential_primaries', to='candidates.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyParliamentaryPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_parliamentary_primaries', to='candidates.presidentialcandidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_parliamentary_primaries', to='candidates.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyFlagBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('flag_bearer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_flag_bearers', to='candidates.presidentialcandidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_flag_bearers', to='candidates.party')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parl_can_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.models.upload_parl_can_photo_path)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('candidate_type', models.CharField(blank=True, choices=[('Independent', 'Independent'), ('Main Stream', 'Main Stream')], max_length=100, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consti_parlia_candidate', to='regions.constituency')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlia_candidate_party', to='candidates.party')),
            ],
        ),
    ]
