# Generated by Django 4.2.16 on 2024-09-18 04:51

from django.db import migrations, models
import django.db.models.deletion
import regions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('constituency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_year', models.CharField(blank=True, max_length=255, null=True)),
                ('parliamentary_submitted', models.BooleanField(default=False)),
                ('presidential_submitted', models.BooleanField(default=False)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electoral_area_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('electoral_area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_year', models.CharField(blank=True, max_length=255, null=True)),
                ('parliamentary_submitted', models.BooleanField(default=False)),
                ('presidential_submitted', models.BooleanField(default=False)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_electoral_area', to='regions.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('polling_station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('election_year', models.CharField(blank=True, max_length=255, null=True)),
                ('parliamentary_submitted', models.BooleanField(default=False)),
                ('presidential_submitted', models.BooleanField(default=False)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('electoral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_area_polling_stations', to='regions.electoralarea')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initials', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to=regions.models.upload_region_image_path)),
                ('election_year', models.CharField(blank=True, max_length=255, null=True)),
                ('parliamentary_submitted', models.BooleanField(default=False)),
                ('presidential_submitted', models.BooleanField(default=False)),
                ('central_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('central_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionLayerCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_coordinates', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_registered_voters', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStationVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('non_voters', models.IntegerField(default=0)),
                ('turn_out_percent', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_station_registered_voters', to='regions.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStationLayerCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling_station_coordinates', to='regions.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('electoral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_area_registered_voters', to='regions.electoralarea')),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralAreaLayerCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('electoral_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_area_coordinates', to='regions.electoralarea')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyVotersParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_voters', models.IntegerField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('turn_out', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_registered_voters', to='regions.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyLayerCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency_coordinates', to='regions.constituency')),
            ],
        ),
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_constituencies', to='regions.region'),
        ),
    ]
