# Generated by Django 5.1.2 on 2024-10-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencyvotersparticipation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='electoralvotersparticipation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='pollingstationvotersparticipation',
            name='year',
        ),
        migrations.RemoveField(
            model_name='regionalvotersparticipation',
            name='year',
        ),
    ]
