# Generated by Django 5.1.2 on 2024-10-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_remove_constituencyvotersparticipation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencyvotersparticipation',
            name='non_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electoralvotersparticipation',
            name='non_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionalvotersparticipation',
            name='non_voters',
            field=models.IntegerField(default=0),
        ),
    ]
