# Generated by Django 5.1.2 on 2024-10-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_constituencyvotersparticipation_non_voters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituencyvotersparticipation',
            old_name='turn_out',
            new_name='turn_out_percent',
        ),
        migrations.RenameField(
            model_name='electoralvotersparticipation',
            old_name='turn_out',
            new_name='turn_out_percent',
        ),
        migrations.RenameField(
            model_name='regionalvotersparticipation',
            old_name='turn_out',
            new_name='turn_out_percent',
        ),
    ]
