# Generated by Django 4.2.16 on 2024-09-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, choices=[('1992', '1992'), ('1996', '1996'), ('2000', '2000'), ('2000R', '2000R'), ('2004', '2004'), ('2008', '2008'), ('2008R', '2008R'), ('2012', '2012'), ('2016', '2016'), ('2020', '2020'), ('2024', '2024')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionParliamentaryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_parl_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ballot_number', models.IntegerField(blank=True, null=True)),
                ('won', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidates', to='candidates.parliamentarycandidate')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_parliamentary_can_constituency', to='regions.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parl_candidate_election_year', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionPresidentialCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_prez_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ballot_number', models.IntegerField(blank=True, null=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('parliamentary_seat', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidates', to='candidates.presidentialcandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prez_candidate_election_year', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateRegionalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('parliamentary_seat', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_regional', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate', to='elections.electionpresidentialcandidate')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_region', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidatePollingStationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_polling_station', to='elections.election')),
                ('polling_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_polling_station', to='regions.pollingstation')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_polling_station_vote', to='elections.electionpresidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateElectoralAreaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_electoral_area', to='elections.election')),
                ('electoral_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_electoral_area', to='regions.electoralarea')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_electoral_area_vote', to='elections.electionpresidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='PresidentialCandidateConstituencyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidate_constituency', to='regions.constituency')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presidential_candidates_constituency', to='elections.election')),
                ('prez_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidential_candidate_consti_vote', to='elections.electionpresidentialcandidate')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateRegionalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_regional', to='elections.election')),
                ('parl_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate', to='elections.electionparliamentarycandidate')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_region', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidatePollingStationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_polling_station', to='elections.election')),
                ('parl_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_polling_station_vote', to='elections.electionparliamentarycandidate')),
                ('polling_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_polling_station', to='regions.pollingstation')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateElectoralAreaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_electoral_area', to='elections.election')),
                ('electoral_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_electoral_area', to='regions.electoralarea')),
                ('parl_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_electoral_area_vote', to='elections.electionparliamentarycandidate')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryCandidateConstituencyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(default=0)),
                ('total_votes_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('won', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidate_constituency', to='regions.constituency')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parliamentary_candidates_constituency', to='elections.election')),
                ('parl_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_candidate_consti_vote', to='elections.electionparliamentarycandidate')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='first_runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_first_runner_up', to='elections.electionpresidentialcandidate'),
        ),
        migrations.AddField(
            model_name='election',
            name='second_runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_second_runner_up', to='elections.electionpresidentialcandidate'),
        ),
        migrations.AddField(
            model_name='election',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_presidential_winner', to='elections.electionpresidentialcandidate'),
        ),
    ]
